### ISSUE TITLE
DlOpen { desc: "/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33\\' not found

### ISSUE THREAD

**Issue by Syronin** [WilliamVenner/gmod-rs#11]
This is my first time creating a binary module for gmod. Compiling in virtualbox on ubuntu

**Comment by Syronin** [comment]
Previously there was an error /usr/bin/ld: cannot find crti.o: No such file or directory. I fixed it using the command sudo apt install gcc-multilib

**Comment by WilliamVenner** [comment]
The version of glibc installed on your system is newer than what the Gmod server has. You'll need to build on an older release of your distro or build inside a Docker container that uses an older image that has an older glibc version.
