### ISSUE TITLE
lual_loadstring

### ISSUE THREAD

**Issue by ArkovLeChauveV2** [WilliamVenner/gmod-rs#8]
Hi, I'm trying to run a string but the print doesn't show up, i just see "yes" in my console

```
unsafe {
    let code = lua.load_string( lua_string!( "print('zozz')" ) );

    match code {
        Ok( _ ) => println!( "yes" ),
        Err( _ ) => println!( "no" ),
    };
};
```

**Comment by WilliamVenner** [comment]
Check lual_loadstring docs: https://pgl.yoyo.org/luai/i/luaL_loadstring

It does not run the code, but pushes it to the stack as a function, you need to call it

Most functions in this crate are just direct calls to the Lua C API
